/* This code was generated by Akka Serverless tooling.
 * As long as this file exists it will not be re-generated.
 * You are free to make changes to this file.
 */
package iot.domain;

import com.akkaserverless.javasdk.testkit.ValueEntityResult;
import com.akkaserverless.javasdk.valueentity.ValueEntity;
import com.google.protobuf.Empty;
import iot.api.SmartDeviceApi;
import java.util.ArrayList;
import java.util.List;
import java.util.NoSuchElementException;
import org.junit.Test;
import scala.jdk.javaapi.CollectionConverters;

import static org.junit.Assert.*;

public class SmartDeviceTest {

  @Test
  public void exampleTest() {
    SmartDeviceTestKit testKit = SmartDeviceTestKit.of(SmartDevice::new);
    // use the testkit to execute a command
    // of events emitted, or a final updated state:
    // ValueEntityResult<SomeResponse> result = testKit.someOperation(SomeRequest);
    // verify the response
    // SomeResponse actualResponse = result.getReply();
    // assertEquals(expectedResponse, actualResponse);
    // verify the final state after the command
    // assertEquals(expectedState, testKit.getState());
  }

  @Test
  public void connectDeviceTest() {
    SmartDeviceTestKit testKit = SmartDeviceTestKit.of(SmartDevice::new);
    // ValueEntityResult<Empty> result = testKit.connectDevice(SmartDeviceConnected.newBuilder()...build());
  }

}
