/* This code was generated by Akka Serverless tooling.
 * As long as this file exists it will not be re-generated.
 * You are free to make changes to this file.
 */
package iot.domain;

import com.akkaserverless.javasdk.valueentity.ValueEntityContext;
import com.google.protobuf.Empty;
import iot.DeviceApi;

/** A value entity. */
public class Device extends AbstractDevice {
  @SuppressWarnings("unused")
  private final String entityId;

  public Device(ValueEntityContext context) {
    this.entityId = context.entityId();
  }

  @Override
  public DeviceDomain.DeviceState emptyState() {
    return DeviceDomain.DeviceState.getDefaultInstance();
  }

  @Override
  public Effect<Empty> connectDevice(DeviceDomain.DeviceState currentState, DeviceApi.DeviceConnected command) {
    String deviceId = command.getDeviceId();
    String name = command.getName();

    DeviceDomain.DeviceState newState = currentState.toBuilder().setName(name + "_" + deviceId).build();

    return effects().updateState(newState).thenReply(Empty.getDefaultInstance());
  }
}