/* This code was generated by Akka Serverless tooling.
 * As long as this file exists it will not be re-generated.
 * You are free to make changes to this file.
 */
package iot.view;

import com.akkaserverless.javasdk.view.ViewContext;
import iot.domain.DeviceDomain;

public class GetDevicesView extends AbstractGetDevicesView {

  public GetDevicesView(ViewContext context) {}

}
