/* This code was generated by Akka Serverless tooling.
 * As long as this file exists it will not be re-generated.
 * You are free to make changes to this file.
 */

package iot.action;

import com.akkaserverless.javasdk.JsonSupport;
import com.akkaserverless.javasdk.ServiceCallRef;
import com.akkaserverless.javasdk.action.ActionCreationContext;
import com.google.protobuf.Any;
import com.google.protobuf.Descriptors;
import com.google.protobuf.Empty;
import com.google.protobuf.InvalidProtocolBufferException;
import com.google.protobuf.ProtocolMessageEnum;
import iot.api.SmartDeviceApi;
import iot.domain.DeviceDomain;
import iot.domain.SmartDeviceDomain;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.List;

/**
 * An action.
 */
public class DeviceTopicSubscriptionAction extends AbstractDeviceTopicSubscriptionAction {

    private static final Logger log = LoggerFactory.getLogger(DeviceTopicSubscriptionAction.class);
    private final ServiceCallRef<SmartDeviceApi.SmartDeviceConnected> deviceConnectedServiceCallRef;


    public DeviceTopicSubscriptionAction(ActionCreationContext creationContext) {
        deviceConnectedServiceCallRef = creationContext
                .serviceCallFactory()
                .lookup("iot.api.SmartDeviceService", "ConnectDevice", SmartDeviceApi.SmartDeviceConnected.class);
    }

    @Override
    public Effect<Empty> connect(DeviceDomain.DeviceState deviceState) {


        String deviceId = deviceState.getId();
        String deviceName = deviceState.getName();
        String currentValue = deviceState.getValue();
        DeviceDomain.DeviceType deviceType = deviceState.getType();

        log.info("Handler for Smart Device Connected id={}, name={}, val={} - Sending API call", deviceId, deviceName, currentValue);

        SmartDeviceApi.SmartDeviceConnected deviceConnected = SmartDeviceApi.SmartDeviceConnected.newBuilder()
                .setDeviceId(deviceId)
                .setDeviceName(deviceName)
                .setCurrentValue(currentValue)
                .build();

        return effects().forward(deviceConnectedServiceCallRef.createCall(deviceConnected));
    }
}
