/* This code was generated by Akka Serverless tooling.
 * As long as this file exists it will not be re-generated.
 * You are free to make changes to this file.
 */

package iot;

import com.akkaserverless.javasdk.action.ActionCreationContext;
import iot.domain.DeviceDomain;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * An action.
 */
public class DeviceStatePublishingServiceAction extends AbstractDeviceStatePublishingServiceAction {

    private static final Logger log = LoggerFactory.getLogger(DeviceStatePublishingServiceAction.class);

    public DeviceStatePublishingServiceAction(ActionCreationContext creationContext) {
    }

    @Override
    public Effect<DeviceDomain.DeviceState> publishDeviceState(DeviceDomain.DeviceState deviceState) {
        final String deviceId = deviceState.getId();
        final String deviceName = deviceState.getName();
        final String currentValue = deviceState.getValue();

        log.info("PublishDeviceState id={}, name={}, val={}", deviceId, deviceName, currentValue);

        return effects().reply(deviceState);
    }
}