/* This code was generated by Akka Serverless tooling.
 * As long as this file exists it will not be re-generated.
 * You are free to make changes to this file.
 */

package iot;

import com.akkaserverless.javasdk.AkkaServerless;
import com.typesafe.config.Config;
import com.typesafe.config.ConfigFactory;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import iot.action.DeviceTopicSubscriptionAction;
import iot.domain.SmartDevice;

public final class Main {

  private static final Logger LOG = LoggerFactory.getLogger(Main.class);

  public static AkkaServerless createAkkaServerless() {
    // The AkkaServerlessFactory automatically registers any generated Actions, Views or Entities,
    // and is kept up-to-date with any changes in your protobuf definitions.
    // If you prefer, you may remove this and manually register these components in a
    // `new AkkaServerless()` instance.
    return AkkaServerlessFactory.withComponents(
      SmartDevice::new,
      DeviceTopicSubscriptionAction::new);
  }

  public static void main(String[] args) throws Exception {
    LOG.info("starting the Akka Serverless service");

    Config config = ConfigFactory.load(ConfigFactory.parseString("  akkaserverless {\n" +
            "      user-function-port = 8082\n" +
            "      system.akka {\n" +
            "      }\n" +
            "    }"));

    createAkkaServerless().start(config);
  }
}
